trigger:
- main  # Replace 'main 

pr:
- '*'

pool:
  name: kaka

steps:
- script: |
    # Install Azure CLI
    cd $(Agent.BuildDirectory)/s/pipeline
    pwd
    chmod +x githubbranch.sh
    ./githubbranch.sh
  displayName: 'Terraform Plan & Apply'
