trigger:
- main  # Replace 'main with main' 

pr:
- '*'

pool:
  name: Azure Pipelines

jobs:
- job: checkbranchstatus
  steps:
  - script: |
      cd $(Agent.BuildDirectory)/s/pipeline
      chmod +x githubbranch.sh
      ./githubbranch.sh

    displayName: 'Precheck'
    continueOnError: false  # Allow the step to continue, even if it fails

- job: terraform
  dependsOn: checkbranchstatus
  steps:
  - script: |
      # This job will only run if the previous job succeeded
      echo "This job runs because the first job succeeded"
    displayName: 'Main job'
