trigger:
- main  # Replace 'main with main' 

pr:
- '*'

pool:
  name: tcl

jobs:
- job: checkbranchstatus
  steps:
  - script: |
      CURRENT_BRANCH=$(Build.SourceBranch)
      pwd
      ls
      cd $(Agent.BuildDirectory)/s/pipeline
      pwd
      ls
      chmod +x githubbranch.sh
      ./githubbranch.sh "$CURRENT_BRANCH"

    displayName: 'Precheck'
    continueOnError: false  # Allow the step to continue, even if it fails

- job: terraform
  dependsOn: checkbranchstatus
  steps:
  - script: |
      # This job will only run if the previous job succeeded
      echo "This job runs because the first job succeeded"
    displayName: 'Main job'
