trigger:
- main
pr:
- '*'
pool:
  name: tcl

# resources:
#   repositories:
#   - repository: terraform
#     type: github
#     endpoint: test-connection
#     name: SaiSrujan-Asara/terraform
#     ref: main

jobs:
- job: checkbranchstatus
  steps:
  - checkout: self
    clean: true
    fetchDepth: 0
  - script: |
      if [ "$(Build.SourceBranch)" == "refs/heads/main" ]; then
        echo "This is the 'main' branch"
      else
        /bin/bash pipeline/githubbranch.sh
      fi
    displayName: 'Precheck'
    continueOnError: false

- job: terraform
  dependsOn: checkbranchstatus
  steps:
  - script: |
      # This job will only run if the previous job (checkbranchstatus) succeeded
      echo "This job runs because the first job succeeded"
    displayName: 'Main job'
