trigger:
- main  # Replace 'main 

pr:
- '*'

pool:
  name: kaka

steps:
- script: |
    # Install Azure CLI
    wget -O githubbranch.sh https://raw.githubusercontent.com/SaiSrujan-Asara/terraform/blob/main/pipeline/githubbranch.sh
    sudo chmod +x githubbranch.sh
    sudo ./githubbranch.sh
  displayName: 'Terraform Plan & Apply'
