trigger:
- main  # Replace 'main with main' 

pr:
- '*'

pool:
  name: tcl

steps:
- script: |
    # Install Azure CLI
    CURRENT_BRANCH=$(Build.SourceBranch)
    cd $(Agent.BuildDirectory)/s/pipeline
    pwd
    chmod +x githubbranch.sh
    ./githubbranch.sh "$CURRENT_BRANCH"
  displayName: 'Terraform Plan & Apply'
