trigger:
- main
pr:
- '*'
pool:
  name: tcl

# resources:
#   repositories:
#   - repository: terraform
#     type: github
#     endpoint: test-connection
#     name: SaiSrujan-Asara/terraform
#     ref: main

jobs:
- job: checkbranchstatus
  # condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
  steps:
  - checkout: self
    clean: true
    fetchDepth: 0
  - script: |
      /bin/bash pipeline/githubbranch.sh
    displayName: 'Precheck'
    continueOnError: false

- job: terraform
  dependsOn: checkbranchstatus
  steps:
  - script: |
      # This job will only run if the previous job succeeded
      echo "This job runs because the first job succeeded"
    displayName: 'Main job'
