trigger:
- main  # Replace 'main with main' 

pr:
- '*'

pool:
  name: tcl

jobs:
- job: checkbranchstatus
  steps:
  - script: |
       branch_reference="$BUILD_SOURCEBRANCH"
       branch_name=${branch_reference#refs/heads/}
       echo "Branch Name: $branch_name"
    #   /bin/bash pipeline/githubbranch.sh 
    # displayName: 'Precheck'
    # continueOnError: false  # Allow the step to continue, even if it Fails
    # variables: 
    #   BRANCH_NAME: echo Build_SourceBranch

- job: terraform
  dependsOn: checkbranchstatus
  steps:
  - script: |
      # This job will only run if the previous job succeeded
      echo "This job runs because the first job succeeded"
    displayName: 'Main job'
