trigger:
- main  # Replace 'main with main' 

pr:
- '*'

pool:
  name: tcl

jobs:
- job: checkbranchstatus
  steps:
  - script: |
      # branch_reference="$BUILD_SOURCEBRANCHNAME"
      # branch_name=${branch_reference#refs/heads/}
      # git checkout "$branch_name"
      # /bin/bash pipeline/branch.sh 
      # Fetch the latest changes from the remote main branch
      git fetch

      # Check out the feature branch
      # git checkout main

      # Merge the latest changes from the main branch into the feature branch
      git merge "origin/main"

      # Push the updated feature branch back to the remote repository
      git push origin main
      
    displayName: 'Precheck'
    continueOnError: false  # Allow the step to continue, even if it Fails
    # variables: 
    #   BRANCH_NAME: echo Build_SourceBranch

- job: terraform
  dependsOn: checkbranchstatus
  steps:
  - script: |
      # This job will only run if the previous job succeeded
      echo "This job runs because the first job succeeded"
    displayName: 'Main job'
