trigger:
- main  # Replace 'main' with your branch name

pr:
- '*'

pool:
  name: test

steps:
- script: |
    # Install Azure CLI
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    # Authenticate with Azure
    az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
    az account set --subscription $(subscriptionId)

    # Terraform setup and execution
    cd $(Build.SourcesDirectory)/path/to/terraform/code
    terraform init
    terraform plan -out=tfplan
    terraform apply -input=false -auto-approve tfplan
  displayName: 'Terraform Plan & Apply'
